  variable "project" {}
  variable "region" {}
  variable "database_version" {}
  variable "tier" {}
  variable "db_instance_name" {}
  variable "disk_autoresize" {}
  variable "disk_size" {}
  variable "disk_type" {}
  variable "db_name" {}
  variable "db_charset" {}
  variable "db_collation" {}
  variable "user_name" {}
  variable "user_host" {}
  variable "user_password" {}
  variable "count" {}
  variable "compute_address" {}