  variable "public_key_path" {}
  variable "private_key_path" {}
  variable "image" {}
  variable "instance_name_web" {}
  variable "count_web" {}
  variable "machine_type_web" {}
  variable "instance_name_bastion" {}
  variable "machine_type_bastion" {}
  variable "private_subnetwork" {}