---
- name: Install dependencies
  package:
    name:
      - java-1.8.0-openjdk
    state: latest

- name: install the latest version of Apache Maven
  yum:
    name: maven
    state: latest

- name: Download jenkins repo
  get_url:
    url: "{{ jenkins_download_url }}"
    dest: "{{ jenkins_repo_path }}"

- name: Import Jenkins CI key 
  rpm_key:
    key: "{{jenkins_key_url}}"
    state: present
 
- name: Install Jenkins
  package:
    name: jenkins
    state: latest
 
- name: Start the server
  service:
    name: jenkins
    state: started
- wait_for: 
    port: 8080
...